import { useState } from "react";
import { ArrowRight, ChevronDown, Download, Sparkles } from "lucide-react";
import Card from "../ui/Card.jsx";
import Button from "../ui/Button.jsx";
import { Field, inputCls } from "../ContentForm.jsx";
import GeneratorHeader from "./GeneratorHeader.jsx";
import { faqs, faqGeneratorConfig } from "../../data/mock.js";

export default function FAQGenerator() {
  const [active, setActive] = useState(0);
  const [answers, setAnswers] = useState(true);
  const [busy, setBusy] = useState(false);

  /*
   * IMPORTANT:
   *
   * generatedFaqs contains ONLY the FAQs that have actually
   * been generated by clicking the Generate button.
   *
   * Selecting a number in the form does NOT modify this.
   */
  const [generatedFaqs, setGeneratedFaqs] = useState([]);

  const [formData, setFormData] = useState({
    topic: faqGeneratorConfig.fields.topic.defaultValue,
    targetAudience: faqGeneratorConfig.fields.targetAudience.options[0],
    numberOfFaqs: faqGeneratorConfig.fields.numberOfFaqs.options[0],
    tone: faqGeneratorConfig.fields.tone.options[0],
  });

  const updateField = (field, value) => {
    setFormData((current) => ({
      ...current,
      [field]: value,
    }));

    /*
     * Do NOT change generatedFaqs here.
     *
     * The selected number only becomes effective
     * when Generate is clicked.
     */
  };

  /*
   * Convert the selected FAQ count into a number.
   *
   * Supports values such as:
   *
   * "5"
   * "10"
   * "5 FAQs"
   * "10 FAQs"
   */
  const getFaqCount = () => {
    const value = String(formData.numberOfFaqs);

    const match = value.match(/\d+/);

    return match ? Number(match[0]) : 0;
  };

  /*
   * Generate FAQs.
   *
   * This is the ONLY place where generatedFaqs changes.
   */
  const generate = () => {
    setBusy(true);

    const numberOfFaqs = getFaqCount();

    setTimeout(() => {
      /*
       * Use the selected number only after
       * the user clicks Generate.
       */
      const generated = faqs.slice(0, numberOfFaqs);

      setGeneratedFaqs(generated);

      setActive(0);
      setBusy(false);
    }, 800);
  };

  /*
   * Export only FAQs that have actually been generated.
   */
  const exportTxt = () => {
    if (generatedFaqs.length === 0) {
      return;
    }

    const txt = generatedFaqs
      .map(([q, a], i) => {
        return `${i + 1}. ${q}${answers ? `\n${a}` : ""}`;
      })
      .join("\n\n");

    const blob = new Blob([txt], {
      type: "text/plain;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);

    const el = document.createElement("a");

    el.href = url;
    el.download = faqGeneratorConfig.exportFileName;

    document.body.appendChild(el);
    el.click();
    document.body.removeChild(el);

    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <GeneratorHeader
        title={faqGeneratorConfig.title}
        description={faqGeneratorConfig.description}
      >
        <Button onClick={exportTxt} disabled={generatedFaqs.length === 0}>
          <Download />
          {faqGeneratorConfig.exportLabel}
        </Button>
      </GeneratorHeader>

      <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)]">
        {/* =================================================
            FORM
        ================================================= */}

        <Card className="p-4">
          <h2 className="mb-4 font-bold">1. Enter Details</h2>

          <div className="space-y-4">
            {/* Topic */}

            <Field label={faqGeneratorConfig.fields.topic.label}>
              <input
                className={inputCls}
                value={formData.topic}
                onChange={(e) => updateField("topic", e.target.value)}
              />
            </Field>

            {/* Target Audience */}

            <Field label={faqGeneratorConfig.fields.targetAudience.label}>
              <select
                className={inputCls}
                value={formData.targetAudience}
                onChange={(e) => updateField("targetAudience", e.target.value)}
              >
                {faqGeneratorConfig.fields.targetAudience.options.map(
                  (option) => (
                    <option key={option} value={option}>
                      {option}
                    </option>
                  ),
                )}
              </select>
            </Field>

            {/* Number of FAQs */}

            <Field label={faqGeneratorConfig.fields.numberOfFaqs.label}>
              <select
                className={inputCls}
                value={formData.numberOfFaqs}
                onChange={(e) => updateField("numberOfFaqs", e.target.value)}
              >
                {faqGeneratorConfig.fields.numberOfFaqs.options.map(
                  (option) => (
                    <option key={option} value={option}>
                      {option}
                    </option>
                  ),
                )}
              </select>
            </Field>

            {/* Tone */}

            <Field label={faqGeneratorConfig.fields.tone.label}>
              <select
                className={inputCls}
                value={formData.tone}
                onChange={(e) => updateField("tone", e.target.value)}
              >
                {faqGeneratorConfig.fields.tone.options.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </Field>

            {/* Include Answers */}

            <label className="flex items-center justify-between text-xs font-semibold">
              {faqGeneratorConfig.includeAnswersLabel}

              <input
                type="checkbox"
                checked={answers}
                onChange={(e) => setAnswers(e.target.checked)}
                className="size-4 accent-green-600"
              />
            </label>

            {/* Generate */}

            <Button className="h-11 w-full" onClick={generate} disabled={busy}>
              <Sparkles />

              {busy
                ? faqGeneratorConfig.generateButton.busy
                : faqGeneratorConfig.generateButton.idle}

              <ArrowRight />
            </Button>
          </div>
        </Card>

        {/* =================================================
            GENERATED FAQs
        ================================================= */}

        <Card
          className={`overflow-hidden transition ${busy ? "opacity-50" : ""}`}
        >
          <div className="border-b border-slate-200 px-4 py-3">
            <h2 className="font-bold">{faqGeneratorConfig.generatedTitle}</h2>

            {generatedFaqs.length > 0 && (
              <p className="mt-1 text-xs text-slate-500">
                {generatedFaqs.length} FAQs generated
              </p>
            )}
          </div>

          {generatedFaqs.length > 0 ? (
            generatedFaqs.map(([q, a], i) => (
              <div
                key={`${q}-${i}`}
                className="border-b border-slate-100 last:border-0"
              >
                <button
                  type="button"
                  onClick={() => setActive(active === i ? -1 : i)}
                  aria-expanded={active === i}
                  className="flex w-full items-start gap-3 px-4 py-3 text-left hover:bg-slate-50"
                >
                  <span className="grid size-6 shrink-0 place-items-center rounded-full bg-green-50 text-[11px] font-bold text-green-700">
                    {i + 1}
                  </span>

                  <span className="flex-1 text-sm font-semibold text-slate-800">
                    {q}
                  </span>

                  <ChevronDown
                    className={`mt-0.5 size-4 shrink-0 text-slate-400 transition ${
                      active === i ? "rotate-180" : ""
                    }`}
                  />
                </button>

                {active === i && answers && (
                  <p className="px-4 pb-4 pl-[52px] text-xs leading-6 text-slate-600">
                    {a}
                  </p>
                )}
              </div>
            ))
          ) : (
            <div className="flex min-h-[300px] items-center justify-center px-6 text-center">
              <div>
                <Sparkles className="mx-auto mb-3 size-8 text-slate-300" />

                <h3 className="font-semibold text-slate-700">
                  No FAQs generated yet
                </h3>

                <p className="mt-1 text-xs leading-5 text-slate-500">
                  Fill in the settings and click Generate to create your FAQ
                  suggestions.
                </p>
              </div>
            </div>
          )}
        </Card>
      </div>
    </div>
  );
}
